{"name": "test_login_fail[test_info1]", "status": "passed", "attachments": [{"name": "stdout", "source": "7447c57f-fd08-47d6-8393-f2b5681c6a8a-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_info", "value": "{'mobile': '13502811019', 'pwd': '123456', 'expected': '手机号码或密码错误！请联系管理人员。'}"}], "start": 1611562752268, "stop": 1611562756134, "uuid": "5f174944-ae24-424e-93eb-f00de7f2ece6", "historyId": "a2e1e6ff4a78458533bb1da47a2a7f22", "testCaseId": "912ae1978968c73f58f65a524468c60c", "fullName": "cases.login_test.TestLogin#test_login_fail", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "staging"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20170703AYCC"}, {"name": "thread", "value": "16400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.login_test"}]}