{"name": "test_login_fail[test_info2]", "status": "passed", "attachments": [{"name": "stdout", "source": "ace4c81f-0e69-4913-bda0-8ff9663a9ae9-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "test_info", "value": "{'mobile': '13502811011', 'pwd': '123123', 'expected': '手机号码或密码错误！请联系管理人员。'}"}], "start": 1611562756139, "stop": 1611562760038, "uuid": "6eb38010-09c2-441e-ae0f-a8ae6f7b45c4", "historyId": "402601c933ab00fb733b14a35e18f3bf", "testCaseId": "912ae1978968c73f58f65a524468c60c", "fullName": "cases.login_test.TestLogin#test_login_fail", "labels": [{"name": "tag", "value": "login"}, {"name": "tag", "value": "staging"}, {"name": "parentSuite", "value": "cases"}, {"name": "suite", "value": "login_test"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-20170703AYCC"}, {"name": "thread", "value": "16400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.login_test"}]}